#!/usr/bin/env python3
"""
gen_index.py — regenerate codebase-map/repos/_index.md from the actual shadow files.

Run this whenever shadow docs are added, removed, or renamed. The output is
deterministic: alpha-sorted, identical content given identical inputs.

Stdlib only.
"""
from __future__ import annotations

import collections
import re
import sys
from pathlib import Path

MAP_REPOS = Path.home() / "projects" / "codebase-map" / "repos"
INDEX = MAP_REPOS / "_index.md"

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
FIELDS = ["stack", "domain", "shape", "status"]


def parse_frontmatter(text: str) -> dict[str, str]:
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}
    out: dict[str, str] = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, _, v = line.partition(":")
            out[k.strip()] = v.strip()
    return out


def main() -> int:
    shadows = sorted(p for p in MAP_REPOS.glob("*.md") if not p.name.startswith("_"))
    rows = []
    status_counts: collections.Counter[str] = collections.Counter()
    stack_counts: collections.Counter[str] = collections.Counter()
    domain_counts: collections.Counter[str] = collections.Counter()
    for p in shadows:
        fm = parse_frontmatter(p.read_text())
        rows.append((p.stem, fm.get("stack", "?"), fm.get("domain", "?"), fm.get("shape", "?"), fm.get("status", "?")))
        status_counts[fm.get("status", "?")] += 1
        stack_counts[fm.get("stack", "?")] += 1
        domain_counts[fm.get("domain", "?")] += 1

    lines: list[str] = [
        "# Shadow Doc Index",
        "",
        f"Auto-generated by `scripts/gen_index.py`. **Do not edit by hand** — your changes will be overwritten on the next regen. Regenerate after any add/rename/remove of a shadow doc:",
        "",
        "```",
        "python3 ~/projects/codebase-map/scripts/gen_index.py",
        "```",
        "",
        f"Coverage: **{len(shadows)} shadow docs** out of 232 repos under `~/projects/ship-cars-usa/`.",
        "",
        "## Index",
        "",
        "| # | Repo | Stack | Domain | Shape | Status |",
        "|---|---|---|---|---|---|",
    ]
    for i, (repo, stack, domain, shape, status) in enumerate(rows, 1):
        lines.append(f"| {i} | [{repo}]({repo}.md) | {stack} | {domain} | {shape} | {status} |")

    lines.extend([
        "",
        "## Status counts",
        "",
        "| Status | Count |",
        "|---|---|",
    ])
    for s in ("seed", "verified", "stub", "stale"):
        lines.append(f"| {s} | {status_counts.get(s, 0)} |")

    lines.extend([
        "",
        "## Stack distribution",
        "",
        "| Stack | Count |",
        "|---|---|",
    ])
    for stack, c in stack_counts.most_common():
        lines.append(f"| {stack} | {c} |")

    lines.extend([
        "",
        "## Domain distribution",
        "",
        "| Domain | Count |",
        "|---|---|",
    ])
    for domain, c in domain_counts.most_common():
        lines.append(f"| {domain} | {c} |")

    lines.append("")
    INDEX.write_text("\n".join(lines))
    print(f"wrote {INDEX} ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
